name: MobArmory
author: PuckiSilver
version: v1.0.0
output: build
require:
  - bolt
  - plugins.fancy_armor.setup

data_pack:
  load:
    - libs/dp/*
    - src
  name: MobArmory
  description: Adds mob themed equipment

resource_pack:
  load:
    - libs/rp/*
    - src
  name: MobArmory-RP
  description: Adds mob themed equipment

pipeline:
  - mecha
  - plugins.fancy_armor.fancify
  - plugins.remove_empty_functions
  - plugins.credit
meta:
  credit: [psmoba]
  mecha:
    commands: "https://raw.githubusercontent.com/misode/mcmeta/summary/commands/data.json"
