name: MobArmory
author: PuckiSilver
version: v1.0.1
output: build
require:
  - bolt
  - plugins.fancy_armor.setup

data_pack:
  load:
    - libs/dp/*
    - src
  name: MobArmory
  description: Collect powerful armor themed around mobs and gain their unique abilities
  pack_format: 41

resource_pack:
  load:
    - libs/rp/*
    - src
  name: MobArmory-RP
  description: Collect powerful armor themed around mobs and gain their unique abilities
  pack_format: 32

pipeline:
  - mecha
  - plugins.fancy_armor.fancify
  - plugins.remove_empty_functions
  - plugins.credit
meta:
  credit: [psmoba]
